replicaCount: 3

config:
  inCluster: true
  pluginsDir: /headlamp/static-plugins
  unsafeUseServiceAccountToken: false

serviceAccount:
  create: true
  name: headlamp

clusterRoleBinding:
  create: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
