apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-runtime
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  source:
    repoURL: https://github.com/SattyaPiseth/gitops-platform.git
    targetRevision: main
    path: clusters/production/argocd/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      # Required when Argo CD manages its own workloads and CRDs.
      - ServerSideApply=true
