apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitlab

  sources:
    # Source 1: official GitLab Helm chart
    - repoURL: https://charts.gitlab.io/
      chart: gitlab-runner
      targetRevision: 0.68.1
      helm:
        releaseName: gitlab-runner
        valueFiles:
          - $values/helm-values/gitlab-runner/values.yaml

    # Source 2: values from git repository
    - repoURL: https://github.com/SattyaPiseth/gitops-platform.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
