apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: gitlab

  sources:

    #
    # Source 1:
    # Official GitLab Helm chart.
    #
    - repoURL: https://charts.gitlab.io/
      chart: gitlab

      #
      # PINNED!
      #
      targetRevision: 10.2.4

      helm:
        releaseName: gitlab

        valueFiles:
          - $values/helm-values/gitlab/values.yaml
          - $values/helm-values/gitlab/values-production.yaml


    #
    # Source 2:
    # Your GitOps repository.
    #
    - repoURL: https://github.com/SattyaPiseth/gitops-platform.git

      targetRevision: main

      ref: values


  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab


  revisionHistoryLimit: 10


  syncPolicy:

    #
    # No automated version deployment.
    #
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true


  ignoreDifferences: []