apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    # Source 1: official Helm chart
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.43.0
      helm:
        releaseName: headlamp
        valueFiles:
          - $values/helm-values/headlamp/values.yaml

    # Source 2: values + additional Kubernetes resources
    - repoURL: https://github.com/SattyaPiseth/gitops-platform.git
      targetRevision: main
      ref: values
      path: clusters/production/argocd/resources/headlamp

  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
