apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-barman-cloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    # Source 1: official Helm chart
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: plugin-barman-cloud
      targetRevision: 0.7.1
      helm:
        releaseName: plugin-barman-cloud

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
