apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    # Source 1: official Helm chart
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 34.4.1
      helm:
        releaseName: traefik
        valueFiles:
          - $values/helm-values/traefik/values.yaml

    # Source 2: values from git repository
    - repoURL: https://github.com/SattyaPiseth/gitops-platform.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
