apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Delete=confirm
  name: vault-secrets-operator-system
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argocd
    environment: production
