apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Production Kubernetes platform components

  sourceRepos:
    - https://kubernetes-sigs.github.io/headlamp/
    - https://cloudnative-pg.github.io/charts
    - https://charts.longhorn.io
    - https://prometheus-community.github.io/helm-charts
    - https://postfinance.github.io/kubelet-csr-approver
    - https://traefik.github.io/charts
    - https://github.com/SattyaPiseth/gitops-platform.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: cnpg-system
    - server: https://kubernetes.default.svc
      namespace: headlamp
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: longhorn-system
    - server: https://kubernetes.default.svc
      namespace: traefik

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
