COMPUTED VALUES:
accessLog:
  addInternals: false
  bufferingSize: null
  dualOutput: false
  enabled: true
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names: {}
    names: {}
    queryParameters:
      defaultMode: null
  filters:
    minDuration: ""
    retryAttempts: false
    statusCodes: ""
  format: null
  otlp:
    enabled: false
    grpc:
      enabled: false
      endpoint: ""
      insecure: false
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
    http:
      enabled: false
      endpoint: ""
      headers: {}
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
    resourceAttributes: {}
    serviceName: null
  timezone: ""
additionalArguments: []
additionalVolumeMounts: []
affinity: {}
api:
  basePath: ""
  dashboard: true
  dashboardName: ""
  debug: null
  disableDashboardAd: null
  insecure: false
autoscaling:
  behavior: {}
  enabled: false
  maxReplicas: null
  metrics: []
  minReplicas: null
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ template "traefik.fullname" . }}'
certificatesResolvers: {}
commonLabels: {}
core:
  defaultRuleSyntax: ""
deployment:
  additionalContainers: []
  additionalVolumes: []
  annotations: {}
  dnsConfig: {}
  dnsPolicy: ""
  enabled: true
  goMemLimitPercentage: 0.9
  healthchecksHost: ""
  healthchecksPort: null
  healthchecksScheme: null
  hostAliases: []
  hostUsers: null
  imagePullSecrets: []
  initContainers: []
  kind: Deployment
  labels: {}
  lifecycle: {}
  livenessPath: ""
  minReadySeconds: 0
  podAnnotations: {}
  podLabels: {}
  readinessPath: ""
  replicas: 3
  revisionHistoryLimit: null
  runtimeClassName: ""
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 60
enabled: true
env: []
envFrom: []
experimental:
  abortOnPluginFailure: false
  fastProxy:
    debug: false
    enabled: false
  knative: false
  kubernetesGateway:
    enabled: false
  localPlugins: {}
  otlpLogs: false
  plugins: {}
extraObjects: []
fullnameOverride: ""
gateway:
  annotations: {}
  defaultScope: null
  enabled: true
  infrastructure: {}
  listeners:
    web:
      hostname: ""
      namespacePolicy: null
      port: 8000
      protocol: HTTP
  name: ""
  namespace: ""
gatewayClass:
  enabled: true
  labels: {}
  name: ""
global:
  azure:
    enabled: false
    images:
      hub:
        image: traefik-hub
        registry: ghcr.io/traefik
        tag: latest
      proxy:
        image: traefik
        registry: docker.io/library
        tag: latest
  checkNewVersion: true
  notAppendXForwardedFor: false
  sendAnonymousUsage: false
hostNetwork: false
hub:
  aigateway:
    enabled: false
    maxRequestBodySize: null
  apimanagement:
    admission:
      annotations: {}
      customWebhookCertificate: {}
      listenAddr: ""
      restartOnCertificateChange: true
      secretName: hub-agent-cert
      selfManagedCertificate: false
    enabled: false
    openApi:
      validateRequestMethodAndPath: false
  mcpgateway:
    enabled: false
    maxRequestBodySize: null
  namespaces: []
  offline: null
  pluginRegistry:
    sources: {}
  providers:
    consulCatalogEnterprise:
      cache: false
      connectAware: false
      connectByDefault: false
      constraints: ""
      defaultRule: Host(`{{ normalize .Name }}`)
      enabled: false
      endpoint:
        address: ""
        datacenter: ""
        endpointWaitTime: null
        httpauth:
          password: ""
          username: ""
        scheme: ""
        tls:
          ca: ""
          cert: ""
          insecureSkipVerify: false
          key: ""
        token: ""
      exposedByDefault: true
      namespaces: ""
      partition: ""
      prefix: traefik
      refreshInterval: 15
      requireConsistent: false
      serviceName: traefik
      stale: false
      strictChecks: passing, warning
      watch: false
    microcks:
      auth:
        clientId: ""
        clientSecret: ""
        endpoint: ""
        token: ""
      enabled: false
      endpoint: ""
      pollInterval: 30
      pollTimeout: 5
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: false
        key: ""
    multicluster:
      children:
        cluster-1:
          address: ""
          serversTransport:
            certificates: []
            cipherSuites: []
            disableHTTP2: null
            forwardingTimeouts:
              dialTimeout: null
              idleConnTimeout: null
              pingTimeout: null
              readIdleTimeout: null
              readTimeout: null
              responseHeaderTimeout: null
              writeTimeout: null
            insecureSkipVerify: null
            maxIdleConnsPerHost: null
            maxVersion: ""
            minVersion: ""
            peerCertURI: ""
            rootCAs: []
            serverName: ""
            spiffe:
              ids: []
              trustDomain: ""
      enabled: false
      pollInterval: 5
      pollTimeout: 5
    nutanixPrismCentral:
      allowedVpcs: []
      apiKey: ""
      enabled: false
      endpoint: ""
      filename: ""
      password: ""
      pollInterval: 30
      pollTimeout: 5
      serviceNameCategoryKey: TraefikServiceName
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: false
        key: ""
      username: ""
  redis:
    cluster: null
    database: null
    endpoints: ""
    password: ""
    sentinel:
      masterset: ""
      password: ""
      username: ""
    timeout: ""
    tls:
      ca: ""
      cert: ""
      insecureSkipVerify: false
      key: ""
    username: ""
  sendlogs: null
  token: ""
  tokenMountPath: /etc/secrets
  tracing:
    additionalTraceHeaders:
      enabled: false
      traceContext:
        parentId: ""
        traceId: ""
        traceParent: ""
        traceState: ""
image:
  digest: null
  pullPolicy: IfNotPresent
  registry: null
  repository: null
  tag: null
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik
ingressRoute:
  dashboard:
    annotations: {}
    enabled: false
    entryPoints:
    - traefik
    labels: {}
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    middlewares: []
    services:
    - kind: TraefikService
      name: api@internal
    tls: {}
  healthcheck:
    annotations: {}
    enabled: false
    entryPoints:
    - traefik
    labels: {}
    matchRule: PathPrefix(`/ping`)
    middlewares: []
    services:
    - kind: TraefikService
      name: ping@internal
    tls: {}
instanceLabelOverride: ""
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
log:
  filePath: ""
  format: null
  level: INFO
  noColor: false
  otlp:
    enabled: false
    grpc:
      enabled: false
      endpoint: ""
      insecure: false
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
    http:
      enabled: false
      endpoint: ""
      headers: {}
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
    resourceAttributes: {}
    serviceName: null
metrics:
  addInternals: false
  otlp:
    addEntryPointsLabels: null
    addRoutersLabels: null
    addServicesLabels: null
    enabled: false
    explicitBoundaries: []
    grpc:
      enabled: false
      endpoint: ""
      insecure: false
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
    http:
      enabled: false
      endpoint: ""
      headers: {}
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
    pushInterval: ""
    resourceAttributes: {}
    serviceName: null
  prometheus:
    addEntryPointsLabels: null
    addRoutersLabels: null
    addServicesLabels: null
    buckets: ""
    disableAPICheck: null
    entryPoint: metrics
    headerLabels: {}
    manualRouting: false
    prometheusRule:
      additionalLabels: {}
      apiVersion: monitoring.coreos.com/v1
      enabled: false
      namespace: ""
    service:
      annotations: {}
      enabled: false
      labels: {}
    serviceMonitor:
      additionalLabels: {}
      apiVersion: monitoring.coreos.com/v1
      enableHttp2: false
      enabled: false
      followRedirects: false
      honorLabels: false
      honorTimestamps: false
      interval: ""
      jobLabel: ""
      metricRelabelings: []
      namespace: ""
      namespaceSelector: {}
      relabelings: []
      scrapeTimeout: ""
nameOverride: ""
namespaceOverride: ""
nodeSelector: {}
oci_meta:
  enabled: false
  images:
    hub:
      image: traefik-hub
      tag: latest
    proxy:
      image: traefik
      tag: latest
  repo: traefik
ocsp:
  enabled: false
  responderOverrides: {}
offering_version: ""
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: false
  existingClaim: ""
  name: data
  path: /data
  size: 128Mi
  storageClass: null
  subPath: ""
  volumeName: ""
podDisruptionBudget:
  enabled: false
  maxUnavailable: null
  minAvailable: null
podSecurityContext:
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
ports:
  metrics:
    expose:
      default: false
    exposedPort: 9100
    observability:
      accessLogs: null
      metrics: null
      traceVerbosity: null
      tracing: null
    port: 9100
    protocol: TCP
  traefik:
    expose:
      default: false
    exposedPort: 8080
    hostIP: null
    hostPort: null
    observability:
      accessLogs: null
      metrics: null
      traceVerbosity: null
      tracing: null
    port: 8080
    protocol: TCP
  web:
    allowACMEByPass: false
    asDefault: null
    expose:
      default: true
    exposedPort: 80
    forwardedHeaders:
      insecure: false
      notAppendXForwardedFor: false
      trustedIPs: []
    http:
      redirections:
        entryPoint:
          permanent: true
          scheme: https
          to: websecure
    nodePort: null
    observability:
      accessLogs: null
      metrics: null
      traceVerbosity: null
      tracing: null
    port: 8000
    protocol: TCP
    proxyProtocol:
      insecure: false
      trustedIPs: []
    targetPort: null
    transport:
      keepAliveMaxRequests: null
      keepAliveMaxTime: null
      lifeCycle:
        graceTimeOut: null
        requestAcceptGraceTimeout: null
      respondingTimeouts:
        idleTimeout: null
        readTimeout: null
        writeTimeout: null
    uplink: null
  websecure:
    allowACMEByPass: false
    appProtocol: null
    containerPort: null
    expose:
      default: true
    exposedPort: 443
    forwardedHeaders:
      insecure: false
      notAppendXForwardedFor: false
      trustedIPs: []
    hostPort: null
    http:
      encodedCharacters:
        allowEncodedBackSlash: null
        allowEncodedHash: null
        allowEncodedNullCharacter: null
        allowEncodedPercent: null
        allowEncodedQuestionMark: null
        allowEncodedSemicolon: null
        allowEncodedSlash: null
      maxHeaderBytes: null
      middlewares: []
      sanitizePath: null
      tls:
        certResolver: ""
        domains: []
        enabled: true
        options: ""
    http3:
      advertisedPort: null
      enabled: false
    nodePort: null
    observability:
      accessLogs: null
      metrics: null
      traceVerbosity: null
      tracing: null
    port: 8443
    protocol: TCP
    proxyProtocol:
      insecure: false
      trustedIPs: []
    targetPort: null
    transport:
      keepAliveMaxRequests: null
      keepAliveMaxTime: null
      lifeCycle:
        graceTimeOut: null
        requestAcceptGraceTimeout: null
      respondingTimeouts:
        idleTimeout: null
        readTimeout: null
        writeTimeout: null
priorityClassName: ""
providers:
  file:
    content: {}
    enabled: false
    watch: true
  knative:
    enabled: false
    labelSelector: ""
    namespaces: []
  kubernetesCRD:
    allowCrossNamespace: false
    allowEmptyServices: true
    allowExternalNameServices: false
    crossProviderNamespaces: []
    enabled: true
    ingressClass: ""
    labelSelector: ""
    namespaces: []
    nativeLBByDefault: false
  kubernetesGateway:
    burst: null
    crossProviderNamespaces: []
    enabled: false
    experimentalChannel: false
    labelSelector: ""
    namespaces: []
    nativeLBByDefault: false
    qps: null
    statusAddress:
      hostname: ""
      ip: ""
      service:
        enabled: true
        name: ""
        namespace: ""
  kubernetesIngress:
    allowEmptyServices: true
    allowExternalNameServices: false
    crossProviderNamespaces: []
    disableIngressClassLookup: false
    enabled: true
    ingressClass: traefik
    ingressEndpoint:
      hostname: ""
      ip: ""
    labelSelector: null
    namespaces: []
    nativeLBByDefault: false
    publishedService:
      enabled: true
      pathOverride: ""
    strictPrefixMatching: false
  kubernetesIngressNGINX:
    allowCrossNamespaceResources: null
    allowSnippetAnnotations: null
    certAuthFilePath: ""
    clientBodyBufferSize: null
    controllerClass: k8s.io/ingress-nginx
    customHTTPErrors: []
    defaultBackendService: ""
    disableSvcExternalName: false
    enabled: false
    endpoint: ""
    globalAllowedResponseHeaders: []
    globalAuthUrl: ""
    httpEntryPoint: web
    httpsEntryPoint: websecure
    ingressClass: nginx
    ingressClassByName: false
    ipAllowListStrategy:
      depth: 0
      excludedIPS: []
      ipv6Subnet: 0
    modsec:
      enabled: false
      owaspCoreRules: false
      snippet: ""
    proxyBodySize: null
    proxyBufferSize: null
    proxyBuffering: null
    proxyBuffersNumber: null
    proxyConnectTimeout: null
    proxyNextUpstream: ""
    proxyNextUpstreamTimeout: null
    proxyNextUpstreamTries: null
    proxyReadTimeout: null
    proxyRequestBuffering: null
    proxySendTimeout: null
    publishService:
      enabled: false
      pathOverride: ""
    publishStatusAddress: ""
    strictValidatePathType: null
    throttleDuration: ""
    token: ""
    upstreamKeepaliveTimeout: null
    watchIngressWithoutClass: false
    watchNamespace: ""
    watchNamespaceSelector: ""
  precedence: []
rbac:
  aggregateTo: []
  enabled: true
  namespaced: false
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
resources: {}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
service:
  additionalServices: {}
  annotations: {}
  annotationsTCP: {}
  annotationsUDP: {}
  enabled: true
  labels: {}
  nameOverride: ""
  single: true
  spec:
    type: LoadBalancer
serviceAccount:
  name: ""
serviceAccountAnnotations: {}
startupProbe: {}
tlsOptions: {}
tlsStore: {}
tolerations: []
topologySpreadConstraints: []
tracing:
  addInternals: false
  capturedRequestHeaders: []
  capturedResponseHeaders: []
  otlp:
    enabled: false
    grpc:
      enabled: false
      endpoint: ""
      insecure: false
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
    http:
      enabled: false
      endpoint: ""
      headers: {}
      tls:
        ca: ""
        cert: ""
        insecureSkipVerify: null
        key: ""
  resourceAttributes: {}
  safeQueryParams: []
  sampleRate: null
  serviceName: null
updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
versionOverride: ""
volumes: []
