apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-vault-auth
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/component: grafana
    app.kubernetes.io/managed-by: argocd

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: grafana-vault-auth
  namespace: monitoring
spec:
  vaultConnectionRef: vault-secrets-operator-system/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    audiences:
      - vault
    role: grafana-monitoring
    serviceAccount: grafana-vault-auth
