apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/component: grafana
    app.kubernetes.io/managed-by: argocd
spec:
  type: kv-v2
  mount: kv
  path: monitoring/grafana
  vaultAuthRef: grafana-vault-auth
  destination:
    name: grafana-admin-credentials
    create: true
  syncPeriod: 5m
