apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-minio
  labels:
    app.kubernetes.io/part-of: object-storage
    app.kubernetes.io/managed-by: argocd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: ext4
  dataLocality: strict-local
  dataEngine: v1
