apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-vault-auth
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik-dashboard
    app.kubernetes.io/component: authentication
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
