apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: traefik-dashboard-basic-auth
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik-dashboard
    app.kubernetes.io/component: authentication
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: kv-v2
  mount: kv
  path: traefik/dashboard-basic-auth
  vaultAuthRef: traefik-vault-auth
  destination:
    name: dashboard-basic-auth-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
  refreshAfter: 5m
