apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: minio-internal-tls
  namespace: minio-system
  labels:
    app.kubernetes.io/part-of: object-storage
    app.kubernetes.io/managed-by: argocd
spec:
  serverName: minio.minio-system.svc.cluster.local
  insecureSkipVerify: false
  minVersion: VersionTLS12
  rootCAs:
    - secret: minio-server-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-s3
  namespace: minio-system
  labels:
    app.kubernetes.io/part-of: object-storage
    app.kubernetes.io/managed-by: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`s3.k8s.tss.local`)
      services:
        - kind: Service
          name: minio
          port: 443
          scheme: https
          passHostHeader: true
          serversTransport: minio-internal-tls
  tls:
    secretName: minio-server-tls
