global:
  edition: ce

  hosts:
    domain: k8s.tss.local

    gitlab:
      name: gitlab.k8s.tss.local
      https: true

    registry:
      name: registry.k8s.tss.local
      https: true

    kas:
      name: kas.k8s.tss.local

  gatewayApi:
    enabled: false
    installEnvoy: false
    configureCertmanager: false

  ingress:
    enabled: true
    provider: traefik
    class: traefik

    # Kubernetes 1.35
    apiVersion: networking.k8s.io/v1
    configureCertmanager: false

    tls:
      enabled: true

  hpa:
    apiVersion: autoscaling/v2

  pdb:
    apiVersion: policy/v1

  traefik:
    apiVersion: traefik.io/v1alpha1

  shell:
    port: 22

  revisionHistoryLimit: 5


# Do not deploy GitLab's bundled ingress controller.
nginx-ingress:
  enabled: false


# cert-manager already exists in the platform.
installCertmanager: false


# Keep GitLab's issuer helper inactive.
certmanager-issuer:
  email: ""


# Existing kube-prometheus-stack handles monitoring.
prometheus:
  install: false


# Existing platform Traefik handles ingress.
traefik:
  install: false


gitlab:
  webservice:
    minReplicas: 2

    ingress:
      tls:
        secretName: gitlab-tls

  sidekiq:
    minReplicas: 2

  kas:
    ingress:
      tls:
        secretName: gitlab-kas-tls

  gitlab-shell:
    minReplicas: 2

    traefik:
      ingressClassName: traefik
      entrypoint: gitlab-shell

  toolbox:
    replicas: 1


registry:
  ingress:
    tls:
      secretName: gitlab-registry-tls