apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gitlab-gitaly
  namespace: gitlab
  labels:
    app.kubernetes.io/part-of: gitlab
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      app: gitaly
      release: gitlab
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
